mod callbacks;

use std::env;

use callbacks::SpirvCrossCallbacks;

fn main() {
    let bindings = bindgen::Builder::default()
        .header("spirv-cross-sys/native/wrapper.h")
        .parse_callbacks(Box::new(SpirvCrossCallbacks))
        .allowlist_type("spvc_.*")
        .allowlist_type("SpvBuiltIn_")
        .allowlist_type("SpvCapability_")
        .allowlist_type("SpvDecoration_")
        .allowlist_type("SpvDim_")
        .allowlist_type("SpvExecutionMode_")
        .allowlist_type("SpvExecutionModel_")
        .allowlist_type("SpvFPRoundingMode_")
        .allowlist_type("SpvImageFormat_")
        .allowlist_type("SpvStorageClass_")
        .newtype_enum("SpvBuiltIn_")
        .newtype_enum("SpvCapability_")
        .newtype_enum("SpvDecoration_")
        .newtype_enum("SpvDim_")
        .newtype_enum("SpvExecutionMode_")
        .newtype_enum("SpvExecutionModel_")
        .newtype_enum("SpvFPRoundingMode_")
        .newtype_enum("SpvImageFormat_")
        .newtype_enum("SpvStorageClass_")
        .allowlist_function("spvc.*")
        .rustified_enum("spvc_backend")
        .rustified_enum("spvc_capture_mode")
        .rustified_enum("spvc_result")
        .rustified_enum("spvc_resource_type")
        .rustified_enum("spvc_builtin_resource_type")
        .rustified_enum("spvc_basetype")
        .rustified_enum("spvc_msl_platform")
        .rustified_enum("spvc_msl_index_type")
        .rustified_enum("spvc_msl_shader_variable_format")
        .rustified_enum("spvc_msl_shader_variable_rate")
        .rustified_enum("spvc_msl_sampler_coord")
        .rustified_enum("spvc_msl_sampler_filter")
        .rustified_enum("spvc_msl_sampler_mip_filter")
        .rustified_enum("spvc_msl_sampler_address")
        .rustified_enum("spvc_msl_sampler_compare_func")
        .rustified_enum("spvc_msl_sampler_border_color")
        .rustified_enum("spvc_msl_format_resolution")
        .rustified_enum("spvc_msl_chroma_location")
        .rustified_enum("spvc_msl_component_swizzle")
        .rustified_enum("spvc_msl_sampler_ycbcr_model_conversion")
        .rustified_enum("spvc_msl_sampler_ycbcr_range")
        .bitfield_enum("spvc_hlsl_binding_flag_bits")
        .bitfield_enum("spvc_compiler_option")
        .new_type_alias("spvc_hlsl_binding_flags")
        .new_type_alias("HlslBindingFlags")
        .blocklist_type("spvc_bool")
        .new_type_alias("SpvId")
        .new_type_alias("VariableId")
        .new_type_alias("TypeId")
        .new_type_alias("ConstantId")
        .must_use_type("spvc_result")
        .ctypes_prefix("crate::ctypes")
        .translate_enum_integer_types(true)
        .clang_arg("-Ispirv-cross-sys/native/SPIRV-Cross/")
        .clang_arg("-DSPIRV_CROSS_CLI=OFF")
        .derive_debug(true)
        .derive_partialeq(true)
        .derive_eq(true)
        .derive_hash(true)
        .layout_tests(false)
        .generate()
        .expect("Unable to generate bindings");
    bindings
        .write_to_file(
            env::current_dir()
                .unwrap()
                .join("spirv-cross-sys/src/bindings.rs"),
        )
        .expect("Couldn't write bindings!");
}
